### PR TITLE
Issue39 update version and release

### PR DESCRIPTION
**Pull request by nateschor**
in #39 we incremented the package version # to `1.1.0` and updated the `cran-comments`.

Proposed steps for the PR (can edit):
1. @jmshapir @santiagohermo adjust the wording of [cran-comments.md](https://github.com/JMSLab/eventstudyr/blob/de2c36f114a2acfb1b9fc6fb81cc27aaa019aea9/cran-comments.md) as they see fit. I used the [R Packages](https://r-pkgs.org/release.html#sec-release-cran-comments) book and [dplyr](https://github.com/tidyverse/dplyr/blob/16b472fb2afc50a87502c2b4ed803e2f5f82b9d6/cran-comments.md) `cran-comments.md` files as examples
2. Following https://github.com/JMSLab/eventstudyr/issues/39#issuecomment-1559912707, we make any changes during this PR to the issue 39 branch, and then @ew487 submits the issue39 branch version of the code to CRAN
3. We address any feedback from CRAN. If we're accepted, we merge the issue39 branch changes into `main` and make a release.

Thanks!

### CODE REVIEW

**Review by jmshapir — APPROVED** [review]
@nateschor thanks!

I made a few tweaks to `cran-comments.md` and with those I am good to submit.

**Review by santiagohermo — APPROVED** [review]
Looks good to me, thanks @nateschor!

I would suggest to leave #39 open until CRAN approves the new release

**Comment by jmshapir** [comment]
@santiagohermo thanks!

@nateschor can you remind me of the process to submit to CRAN?

**Comment by nateschor** [comment]
> @santiagohermo thanks!
> 
> @nateschor can you remind me of the process to submit to CRAN?

Please correct me if I'm wrong, but @ew487 (as the package maintainer) pulls in the the most recent version of the code on the issue39 branch and then runs `devtools::release(check = TRUE)` like we did for initial submission in https://github.com/JMSLab/eventstudyr/issues/33#issuecomment-1505630821

Besides for making changes to [cran-comments.md](https://github.com/JMSLab/eventstudyr/blob/976944fc6ec1f5ae54de3a445866412633c7f476/cran-comments.md), I don't think the process for submitting on our end is different for initial submission vs. subsequent submissions after being accepted. 

@jmshapir does that help?

**Comment by jmshapir** [comment]
@nateschor yep that sounds good!

@ew487 can you give https://github.com/JMSLab/eventstudyr/pull/40#issuecomment-1570350310 a try when you have a chance? If it takes more than ~30 minutes of your time please shoot me an e-mail and we'll figure out how best to prioritize.

Thanks!

**Comment by ew487** [comment]
@jmshapir @nateschor 
Yes, sounds good!

**Comment by ew487** [comment]
Update: I have submitted to cran

**Comment by ew487** [comment]
@nateschor Here is the note referred to in the email:

N  checking CRAN incoming feasibility (18.2s)
   Maintainer: 'Emily Wang <emwang@hbs.edu>'
   
   Found the following (possibly) invalid URLs:
     URL: https://cran.r-project.org/web/packages/eventstudyr/eventstudyr.pdf
       From: README.md
       Status: 200
       Message: OK
       CRAN URL not in canonical form
     URL: https://cran.r-project.org/web/packages/eventstudyr/vignettes/documentation.html
       From: README.md
       Status: 200
       Message: OK
       CRAN URL not in canonical form
     The canonical URL of the CRAN page for a package is 
       https://CRAN.R-project.org/package=pkgname
   
   Found the following (possibly) invalid DOIs:
     DOI: 10.1257/aer.20180609
       From: DESCRIPTION
       Status: Forbidden
       Message: 403

**Comment by santiagohermo** [comment]
In order to please CRAN, should we change the URLs in the README to the canonical form @nateschor? The ones below seem to work fine:

- https://cran.r-project.org/package=eventstudyr/eventstudyr.pdf
- https://cran.r-project.org/package=eventstudyr/vignettes/documentation.html

**Comment by nateschor** [comment]
Thanks @santiagohermo! I updated our version number to `1.1.1` and the cran comments in https://github.com/JMSLab/eventstudyr/pull/40/commits/05ffc056f0cedd0c967383a39a814944f99d9f82.

I tried knitting the README again after updating the links to the canonical form you suggest in https://github.com/JMSLab/eventstudyr/pull/40#issuecomment-1575668271, but I'm still having trouble knitting on my end, and want to prevent us losing the graph like [here](https://github.com/JMSLab/eventstudyr/tree/04ed01f43970321ab530be594f7d8c377d398404). This happened the last time I tried knitting the `README.rmd` file.

@santiagohermo would you be able to:
1. Make the 2 canonical URL replacements you suggest
2. Reknit the README to make sure it updates with the plot and new URLs
3. Let @ew487 know when we're good to resubmit our issue39 branch to CRAN

Thank you!

**Comment by jmshapir** [comment]
@santiagohermo @nateschor thanks!

I'm happy to defer to @nateschor on where we implement the seed-setting.

**Comment by santiagohermo** [comment]
Seed added to README @nateschor. We are ready to submit to CRAN again @ew487 !

**Comment by jmshapir** [comment]
@santiagohermo thanks!

@ew487 it would be great if you can resubmit and, as always, reach out if you find it takes more than ~30 minutes to do.

**Comment by nateschor** [comment]
Version `1.1.1` was accepted to CRAN [yesterday](https://cran.r-project.org/web/packages/eventstudyr/index.html)! @ew487 for book keeping purposes can you review this PR (it should only take 5 minutes)? Then based on https://github.com/JMSLab/eventstudyr/issues/39#issuecomment-1559912707 I'll:
* wrap up this PR and merge into `main`
* update the new release draft and have @santiagohermo review it one final time before making the actual release

Thanks!

**Review by ew487 — APPROVED** [review]

**Comment by nateschor** [comment]
Summary [here](https://github.com/JMSLab/eventstudyr/issues/39#issuecomment-1587576380)

**Comment by jmshapir** [comment]
@santiagohermo done thanks!

**Comment by santiagohermo** [comment]
Thanks @jmshapir! I made a small edit to the release to add a zipped file with the built package, as we were doing in previous releases.

**Pull request merged**
