### PR TITLE
PR for #41: Numerical optimization failed for smoothest path in R4.3+

### LINKED ISSUE #41: `Numerical optimization failed` for smoothest path in R4.3+
In the attached example code [`eventstudyr_issue.zip`](https://github.com/JMSLab/eventstudyr/files/11826864/eventstudyr_issue.zip), the smooth path optimization is failing with the example data. Specifically, I see a message that says:
```
Error in FindCoeffs(res_order, coefficients, inv_covar, Wcritic, pN, order,  : 
  Numerical optimization failed when searching for the smoothest path. Please set 'Smpath' to FALSE.
```

I am using `R 4.3.0` on Windows 11.

_code is written below_
```
main <- function() {
    estimates_ols <- EventStudy(
        estimator = "OLS",
        data = example_data,
        outcomevar = "y_jump_m", policyvar = "z",
        idvar      = "id",       timevar   = "t",
        controls = "x_r",
        post = 5, overidpost = 2,
        pre  = 0,  overidpre = 6
    )

    y_breaks = seq(-1, 2, 1)
    plts <- list()

    plts[["smooth_path"]] <- EventStudyPlot(estimates         = estimates_ols,
                                            pre_event_coeffs  = FALSE,
                                            post_event_coeffs = FALSE,
                                            ybreaks           = y_breaks,
                                            smpath            = TRUE) +
                                theme_plots()
}

main()
```

### PR DESCRIPTION
**Pull request by SimonFreyaldenhoven**
closes #41. We increased the tolerance to `1e-4` in the solver for finding the smoothest path. This fixes the error we obtained in some examples were the solver did not converge under the lower tolerance.

### CODE REVIEW

**Comment by SimonFreyaldenhoven** [comment]
@jmshapir I can confirm that I get a reasonable smoothest path or polynomial order 8 under both R 4.2.2 and 4.3.1!

So nothing more on my end!

**Comment by jmshapir** [comment]
@SimonFreyaldenhoven thanks!

I will go ahead and wrap us up here.

If you think it makes sense to push an update to CRAN let me know and I can open a follow-up for that.

**Comment by SimonFreyaldenhoven** [comment]
@jmshapir since there are no other active developments right now, I don't see us making another push to CRAN any time soon. So perhaps it makes sense to push this as a quick bug fix to CRAN?

**Comment by jmshapir** [comment]
@SimonFreyaldenhoven thanks! #44 opened for follow-up.

**Pull request merged**
