### PR TITLE
PR for #44: Release to cran

### LINKED ISSUE #44: Release to CRAN
- [x] Update version number in [DESCRIPTION](https://github.com/JMSLab/eventstudyr/blob/e0df193455bf298e6706b4d1d6575c7e6fe3fa43/DESCRIPTION) to 1.1.2
- [x] Check for [reverse dependencies](https://r-pkgs.org/release.html#sec-release-revdep-checks)
- [x] Update the [comments for CRAN](https://r-pkgs.org/release.html#sec-release-cran-comments)  
- [x] Submit to CRAN
- [ ] On CRAN acceptance, merge to `main` and update github version to harmonize with CRAN

### PR DESCRIPTION
**Pull request by ew487**
Closes #44 

In this issue, we updated the package to version to 1.1.2 and resubmitted to CRAN.

### CODE REVIEW

**Comment by jmshapir** [comment]
@rcalvo12 per e-mail thread, let's try to wrap up the pull this week thanks!

@ew487 fyi.

**Review by rcalvo12 — APPROVED** [review]
@ew487 Thanks for your work here. Changes here look good and I also installed the new version of the package and everything looks good there too. Approving.

**Comment by ew487** [comment]
@rcalvo12 Great! Thanks!

**Comment by ew487** [comment]
Summary [here](https://github.com/JMSLab/eventstudyr/issues/44#issuecomment-1933081286)

**Pull request merged**
